return {
	-- "akinsho/bufferline.nvim",
	-- event = "VeryLazy",
	-- version = "*",
	-- dependencies = "nvim-tree/nvim-web-devicons",
	-- after = "catppuccin",
	--
	-- config = function()
	-- 	vim.opt.termguicolors = true
	-- 	require("bufferline").setup({
	-- 		highlights = require("catppuccin.groups.integrations.bufferline").get(),
	-- 	})
	-- 	-- bufferLine
	-- 	-- vim.keymap.set("n", "th", ":BufferLineCloseLeft<cr>", { desc = "Close Left" })
	-- 	-- vim.keymap.set("n", "tr", ":BufferLineCloseRight<cr>", { desc = "Close Right" })
	-- 	vim.keymap.set("n", "tl", ":BufferLineMoveNext<cr>", { desc = "Move Next" })
	-- 	vim.keymap.set("n", "th", ":BufferLineMovePre<cr>", { desc = "Move Prev" })
	-- 	vim.keymap.set("n", "to", ":BufferLineCloseOthers<cr>", { desc = "Close Others" })
	-- 	vim.keymap.set("n", "L", ":BufferLineCycleNext<cr>", { desc = "Next" })
	-- 	vim.keymap.set("n", "H", ":BufferLineCyclePrev<cr>", { desc = "Preview" })
	-- 	vim.keymap.set("n", "tp", ":BufferLinePick<cr>", { desc = "Pick" })
	-- 	vim.keymap.set("n", "tx", ":BufferLinePickClose<cr>", { desc = "Pick Close" })
	-- end,
}
